import type { CalendarTask, VideoProject, Workspace } from './types.js';
import { normalizeWorkspaceFocus } from './focus.js';
import { syncNextWorkflowMission } from './workflow.js';

const defaultPublishAt = (project: Partial<VideoProject>): string => {
  if (typeof project.publishAt === 'string' && project.publishAt) return project.publishAt;
  const date = typeof project.deadline === 'string' && project.deadline ? project.deadline.slice(0, 10) : new Date().toISOString().slice(0, 10);
  return `${date}T19:00:00`;
};

const migrateProject = (project: Partial<VideoProject>): VideoProject => ({
  ...(project as VideoProject),
  publishAt: defaultPublishAt(project),
  productionCompletedAt: project.productionCompletedAt,
  growthLoopStatus: project.growthLoopStatus ?? (project.status === 'archived' ? 'complete' : project.status === 'repurpose' ? 'repurpose' : project.status === 'analytics-review' ? 'analytics' : 'pending'),
  researchSummary: project.researchSummary ?? '',
  factCheckSummary: project.factCheckSummary ?? '',
  assetPrompts: Array.isArray(project.assetPrompts) ? project.assetPrompts : [],
  capcutBrief: project.capcutBrief ?? '',
  analyticsPostmortem: project.analyticsPostmortem ?? '',
  repurposingPlan: project.repurposingPlan ?? '',
  workflowEvents: Array.isArray(project.workflowEvents) ? project.workflowEvents : [],
});

const migrateTask = (task: Partial<CalendarTask>): CalendarTask => ({
  ...(task as CalendarTask),
  priority: task.priority ?? (task.autoGenerated ? 80 : 30),
  templateKind: task.templateKind ?? (task.autoGenerated ? 'shorts' : 'manual'),
  conflict: task.conflict ?? false,
  conflictReason: task.conflictReason,
});

export const migrateWorkspace = (input: Workspace | Record<string, unknown>): Workspace => {
  const source = structuredClone(input) as unknown as Workspace & { schemaVersion?: number; revision?: number };
  source.schemaVersion = 4;
  source.revision = Math.max(0, Number(source.revision ?? 0));
  source.projects = Array.isArray(source.projects) ? source.projects.map(migrateProject) : [];
  source.calendarTasks = Array.isArray(source.calendarTasks) ? source.calendarTasks.map(migrateTask) : [];
  source.settings = {
    locale: source.settings?.locale ?? 'th',
    timezone: source.settings?.timezone ?? 'Asia/Bangkok',
    weeklyHoursAvailable: source.settings?.weeklyHoursAvailable ?? 12,
    capcutBalance: source.settings?.capcutBalance ?? 0,
    soundEnabled: source.settings?.soundEnabled ?? false,
    reducedMotion: source.settings?.reducedMotion ?? false,
    onboardingComplete: source.settings?.onboardingComplete ?? false,
    workflowMode: source.settings?.workflowMode ?? 'manual',
    aiProvider: source.settings?.aiProvider ?? 'openai',
    openAiModel: source.settings?.openAiModel ?? 'gpt-5.1',
    geminiModel: source.settings?.geminiModel ?? 'gemini-3.5-flash',
    connectedAiEnabled: source.settings?.connectedAiEnabled ?? false,
    connectedAiProxyUrl: source.settings?.connectedAiProxyUrl ?? '/api/ai/generate',
    sqliteStorageEnabled: true,
    activeChannelLimit: source.settings?.activeChannelLimit ?? 2,
    aiMaxOutputTokens: source.settings?.aiMaxOutputTokens ?? 2500,
    aiRequestTimeoutSeconds: source.settings?.aiRequestTimeoutSeconds ?? 60,
    aiDailyBudgetUsd: source.settings?.aiDailyBudgetUsd ?? 2,
    aiMonthlyBudgetUsd: source.settings?.aiMonthlyBudgetUsd ?? 20,
    openAiInputUsdPer1M: source.settings?.openAiInputUsdPer1M ?? 0,
    openAiOutputUsdPer1M: source.settings?.openAiOutputUsdPer1M ?? 0,
    geminiInputUsdPer1M: source.settings?.geminiInputUsdPer1M ?? 0,
    geminiOutputUsdPer1M: source.settings?.geminiOutputUsdPer1M ?? 0,
    workdayStart: source.settings?.workdayStart ?? '09:00',
    workdayEnd: source.settings?.workdayEnd ?? '18:00',
    defaultPublishTime: source.settings?.defaultPublishTime ?? '19:00',
  };
  // Backfill task template kind after project format is known.
  source.calendarTasks = source.calendarTasks.map((task) => {
    const project = source.projects.find((candidate) => candidate.id === task.projectId);
    return {
      ...task,
      templateKind: task.templateKind === 'manual' || task.templateKind === 'growth'
        ? task.templateKind
        : project?.format === 'long' ? 'long' : 'shorts',
    };
  });
  normalizeWorkspaceFocus(source);
  source.projects.filter((project) => project.status !== 'archived').forEach((project) => syncNextWorkflowMission(source, project.id));
  return source;
};
