import type { CalendarTask, VideoProject, Workspace } from './types.js';
import { normalizeWorkspaceFocus } from './focus.js';
import { syncNextWorkflowMission } from './workflow.js';

const migrateProject = (project: Partial<VideoProject>): VideoProject => ({
  ...(project as VideoProject),
  researchSummary: project.researchSummary ?? '',
  factCheckSummary: project.factCheckSummary ?? '',
  assetPrompts: Array.isArray(project.assetPrompts) ? project.assetPrompts : [],
  capcutBrief: project.capcutBrief ?? '',
  analyticsPostmortem: project.analyticsPostmortem ?? '',
  repurposingPlan: project.repurposingPlan ?? '',
  workflowEvents: Array.isArray(project.workflowEvents) ? project.workflowEvents : [],
});

const migrateTask = (task: Partial<CalendarTask>): CalendarTask => ({
  ...(task as CalendarTask),
  priority: task.priority ?? (task.autoGenerated ? 80 : 30),
});

export const migrateWorkspace = (input: Workspace | Record<string, unknown>): Workspace => {
  const source = structuredClone(input) as unknown as Workspace & { schemaVersion?: number };
  source.schemaVersion = 3;
  source.projects = Array.isArray(source.projects) ? source.projects.map(migrateProject) : [];
  source.calendarTasks = Array.isArray(source.calendarTasks) ? source.calendarTasks.map(migrateTask) : [];
  source.settings = {
    locale: source.settings?.locale ?? 'th',
    timezone: source.settings?.timezone ?? 'Asia/Bangkok',
    weeklyHoursAvailable: source.settings?.weeklyHoursAvailable ?? 12,
    capcutBalance: source.settings?.capcutBalance ?? 0,
    soundEnabled: source.settings?.soundEnabled ?? false,
    reducedMotion: source.settings?.reducedMotion ?? false,
    onboardingComplete: source.settings?.onboardingComplete ?? false,
    workflowMode: source.settings?.workflowMode ?? 'manual',
    aiProvider: source.settings?.aiProvider ?? 'openai',
    openAiModel: source.settings?.openAiModel ?? 'gpt-5.1',
    geminiModel: source.settings?.geminiModel ?? 'gemini-3.5-flash',
    connectedAiEnabled: source.settings?.connectedAiEnabled ?? false,
    connectedAiProxyUrl: source.settings?.connectedAiProxyUrl ?? '/api/ai/generate',
    sqliteStorageEnabled: source.settings?.sqliteStorageEnabled ?? true,
    activeChannelLimit: source.settings?.activeChannelLimit ?? 2,
  };
  normalizeWorkspaceFocus(source);
  source.projects.filter((project) => project.status !== 'archived').forEach((project) => syncNextWorkflowMission(source, project.id));
  return source;
};
