import type { CalendarTask, Workspace } from '../domain/types.js';
import { activeChannel, activeProject, projectsInFocus, statusLabels } from '../app/selectors.js';
import { routeHref } from '../app/router.js';
import { addDays, escapeHtml, todayIso } from '../domain/utils.js';
import { taskIsUnlocked, workflowRecommendation, workflowStatusLabels, isProductionComplete } from '../domain/workflow.js';
import { chip, pageHeader } from '../ui/components.js';

const taskColor: Record<CalendarTask['type'], string> = {
  research: 'var(--cyan)', script: 'var(--violet)', editing: 'var(--amber)', upload: 'var(--green)', analytics: 'var(--blue)', rest: 'var(--muted)', other: 'var(--red)',
};
const weekday = (iso: string): string => new Intl.DateTimeFormat('th-TH', { weekday: 'short', day: 'numeric', month: 'short' }).format(new Date(`${iso}T12:00:00`));
const publishValue = (project: { publishAt?: string; deadline: string }, fallbackTime: string): string => project.publishAt?.slice(0,16) || `${project.deadline.slice(0,10)}T${fallbackTime}`;

export const renderCalendar = (workspace: Workspace, params: URLSearchParams): string => {
  const today = todayIso();
  const channel = activeChannel(workspace);
  const requested = workspace.projects.find((item) => item.id === params.get('project'));
  const active = activeProject(workspace);
  const project = requested ?? (active && !isProductionComplete(active) ? active : (workspace.projects.find((item) => !isProductionComplete(item) && item.status !== 'archived') ?? active));
  const projects = projectsInFocus(workspace);
  const projectIds = new Set(projects.map((item) => item.id));
  const tasks = workspace.calendarTasks.filter((task) => !task.projectId || projectIds.has(task.projectId)).toSorted((a,b) => `${a.date}${a.startTime}`.localeCompare(`${b.date}${b.startTime}`));
  const dates = Array.from({ length: 7 }, (_, index) => addDays(today, index));
  const requestedDay = params.get('day');
  const mobileDay = requestedDay && /^\d{4}-\d{2}-\d{2}$/.test(requestedDay) ? requestedDay : today;
  const nextTask = tasks.find((task) => !task.completed && taskIsUnlocked(task, workspace.projects.find((item) => item.id === task.projectId)));
  const recommendation = project ? workflowRecommendation(workspace, project) : undefined;
  const conflicts = tasks.filter((task) => task.autoGenerated && task.conflict && !task.completed);

  const taskCard = (task: CalendarTask): string => {
    const owner = workspace.projects.find((item) => item.id === task.projectId);
    const unlocked = taskIsUnlocked(task, owner);
    const state = task.completed ? 'Done' : task.conflict ? 'Capacity Conflict' : unlocked ? 'On Track' : 'Locked';
    return `<article class="calendar-task-card ${task.completed ? 'done' : ''} ${unlocked ? '' : 'locked'} ${task.conflict ? 'conflict' : ''} ${task.id === workspace.focus.activeTaskId ? 'active' : ''}" style="--task-color:${task.conflict ? 'var(--red)' : taskColor[task.type]}">
      <div class="calendar-task-body"><strong>${escapeHtml(task.title)}</strong><span>${escapeHtml(task.startTime)} · ${task.durationMinutes}m · ${escapeHtml(task.templateKind ?? task.type)}${owner ? ` · ${escapeHtml(owner.title)}` : ''}</span><small class="task-state-text">${escapeHtml(state)}</small>${task.conflict ? `<small class="task-lock-copy">${escapeHtml(task.conflictReason ?? 'Capacity conflict')}</small>` : !unlocked && task.sourceStatus ? `<small class="task-lock-copy">Locked until ${escapeHtml(workflowStatusLabels[task.sourceStatus])}</small>` : ''}</div>
      <div class="calendar-task-actions">${task.completed ? chip('Done','green') : unlocked ? `<button class="btn small" data-action="start-mission" data-project-id="${escapeHtml(owner?.id ?? '')}" data-task-id="${escapeHtml(task.id)}">Start</button>` : chip('Locked','amber')}</div>
    </article>`;
  };

  const projectPlan = project ? `<section class="panel panel-pad"><div class="panel-title"><div><h3>Video plan</h3><p>Topic, Format and Publish datetime are the source of truth for Calendar Planner.</p></div>${isProductionComplete(project) ? chip('✓ Video Complete','green') : chip(project.format === 'long' ? 'Long-form' : 'Shorts','cyan')}</div>
    <div class="data-proof-list"><div><b>Topic</b><span>${escapeHtml(project.title)}</span></div><div><b>Format</b><span>${escapeHtml(project.format)}</span></div><div><b>Publish</b><span>${escapeHtml(publishValue(project, workspace.settings.defaultPublishTime || '19:00').replace('T',' '))}</span></div><div><b>Capacity</b><span>${conflicts.filter((task) => task.projectId === project.id).length ? 'Conflict — reschedule recommended' : 'On track'}</span></div></div>
    ${!isProductionComplete(project) ? `<form class="stack" data-form="reschedule-project" style="margin-top:14px"><input type="hidden" name="projectId" value="${escapeHtml(project.id)}"/><div class="field"><label>Reschedule publish</label><input class="input" type="datetime-local" name="publishAt" value="${escapeHtml(publishValue(project, workspace.settings.defaultPublishTime || '19:00'))}" required/></div><button class="btn" type="submit">Replan around new publish time</button></form>` : '<div class="inline-note success" style="margin-top:14px"><strong>Production complete</strong><br/>Analytics and Repurpose continue in the separate Growth Loop.</div>'}
  </section>` : '';

  const mobileTasks = tasks.filter((task) => task.date === mobileDay);
  const mobileParams = (day: string): Record<string,string> => project ? { day, project: project.id } : { day };

  return `${pageHeader('Calendar','Plan Topic + Format + Publish datetime, then let the capacity-aware planner distribute production work.', `<button class="btn" data-action="export-ics">Export .ics</button>${project ? `<button class="btn" data-action="generate-workflow-plan" data-project-id="${escapeHtml(project.id)}">Rebuild plan</button>` : ''}<a class="btn primary" href="${routeHref('blueprint', channel ? { channel: channel.id } : undefined)}">+ Plan video</a>`)}
    ${conflicts.length ? `<div class="inline-note danger"><strong>Capacity conflict · ${conflicts.length} task${conflicts.length === 1 ? '' : 's'}</strong><br/>Some production work no longer fits before Publish. Reschedule or free capacity.</div>` : ''}
    <section class="calendar-mission-banner"><div><span class="kicker">Next Mission</span><h3>${escapeHtml(nextTask?.title ?? recommendation?.title ?? 'No mission queued')}</h3><p>${nextTask ? `${nextTask.date} · ${nextTask.startTime} · ${nextTask.durationMinutes} min` : recommendation?.detail ?? 'Plan a video to begin.'}</p></div><div class="row wrap">${channel ? chip(channel.name,'cyan') : chip('Portfolio','violet')}${project ? chip(statusLabels[project.status], project.status === 'published' ? 'green' : 'amber') : ''}${nextTask ? `<button class="btn primary" data-action="start-mission" data-project-id="${escapeHtml(nextTask.projectId ?? '')}" data-task-id="${escapeHtml(nextTask.id)}">Start</button>` : ''}</div></section>

    <section class="calendar-mobile-day" aria-label="Single day production schedule"><div class="mobile-day-nav"><a href="${routeHref('calendar', mobileParams(addDays(mobileDay,-1)))}" aria-label="Previous day">←</a><div><strong>${escapeHtml(weekday(mobileDay))}</strong><span>${escapeHtml(mobileDay)}${mobileDay === today ? ' · Today' : ''}</span></div><a href="${routeHref('calendar', mobileParams(addDays(mobileDay,1)))}" aria-label="Next day">→</a></div><div class="stack tight">${mobileTasks.map(taskCard).join('') || '<div class="empty-state"><div><strong>Buffer available</strong><span>No production sessions on this day.</span></div></div>'}</div></section>

    <div class="calendar-layout"><section class="stack">
      <article class="panel calendar-panel desktop-week-calendar"><div class="panel-title"><div><h3>7-day production schedule</h3><p>${channel ? escapeHtml(channel.name) : 'Portfolio'} · ${workspace.settings.weeklyHoursAvailable}h/week capacity</p></div><span class="chip cyan">${escapeHtml(workspace.settings.timezone)}</span></div><div class="calendar-grid">${dates.map((date) => `<div class="day-column ${date === today ? 'today' : ''}"><div class="day-head"><b>${escapeHtml(weekday(date))}</b><span>${date === today ? 'Today' : ''}</span></div><div class="calendar-day-tasks">${tasks.filter((task) => task.date === date).map(taskCard).join('') || '<span class="dim small-copy">Buffer available</span>'}</div></div>`).join('')}</div></article>
      <article class="panel calendar-panel"><div class="panel-title"><div><h3>Video roadmap</h3><p>Production Complete ends at Published; Growth Loop continues without reducing completion.</p></div></div><div class="stack tight">${projects.slice(0,12).map((item) => `<button class="path-card ${item.id === project?.id ? 'active' : ''}" data-action="set-active-project" data-project-id="${escapeHtml(item.id)}"><div class="row between"><strong>${escapeHtml(item.title)}</strong>${isProductionComplete(item) ? chip('✓ Complete','green') : chip(item.format,'cyan')}</div><p>${escapeHtml(statusLabels[item.status])} · Publish ${escapeHtml(publishValue(item, workspace.settings.defaultPublishTime || '19:00').replace('T',' '))}</p></button>`).join('')}</div></article>
    </section><aside class="stack">${projectPlan}<section class="panel panel-pad"><div class="panel-title"><div><h3>Manual task</h3><p>For work outside the generated production workflow.</p></div></div><form class="stack" data-form="calendar-task"><div class="field"><label>Task</label><input class="input" name="title" required placeholder="Review final captions"/></div><div class="form-grid"><div class="field"><label>Date</label><input class="input" type="date" name="date" value="${today}" required/></div><div class="field"><label>Start</label><input class="input" type="time" name="startTime" value="${escapeHtml(workspace.settings.workdayStart || '09:00')}" required/></div></div><div class="form-grid"><div class="field"><label>Duration</label><input class="input" type="number" name="durationMinutes" min="5" value="30"/></div><div class="field"><label>Type</label><select class="select" name="type"><option value="research">Research</option><option value="script">Script</option><option value="editing">Editing</option><option value="upload">Upload</option><option value="analytics">Analytics</option><option value="rest">Rest/buffer</option><option value="other">Other</option></select></div></div><div class="field"><label>Video</label><select class="select" name="projectId"><option value="">Studio task</option>${projects.map((item) => `<option value="${escapeHtml(item.id)}" ${item.id === project?.id ? 'selected' : ''}>${escapeHtml(item.title)}</option>`).join('')}</select></div><div class="field"><label>Recurring</label><select class="select" name="recurring"><option value="none">None</option><option value="daily">Daily</option><option value="weekly">Weekly</option></select></div><button class="btn" type="submit">Add task</button></form></section></aside></div>`;
};
