import type { Workspace } from '../domain/types.js';
import { escapeHtml } from '../domain/utils.js';
import { pageHeader } from '../ui/components.js';
import { icon } from '../ui/icons.js';

export const renderImportExport = (workspace: Workspace): string => `${pageHeader('Import & Export','สำรอง Workspace เป็น Versioned JSON, นำเข้า Analytics CSV และส่ง Calendar .ics โดยไม่พึ่ง Cloud','<button class="btn" data-action="export-workspace">Export JSON</button><button class="btn primary" data-action="export-ics">Export .ics</button>')}
  <div class="import-layout">
    <section class="panel panel-pad"><div class="panel-title"><div><h3>Workspace backup</h3><p>ข้อมูลทั้งหมดอยู่ใน IndexedDB และสำรองเป็น JSON ได้</p></div><span class="chip cyan">Schema v${workspace.schemaVersion}</span></div><div class="drop-zone" id="workspace-drop"><div>${icon('upload')}<strong style="display:block;margin:10px 0 4px;color:var(--text)">Import workspace JSON</strong><span>ลากไฟล์มาวาง หรือเลือกไฟล์จากเครื่อง</span><div style="margin-top:14px"><label class="btn primary" for="workspace-file">Choose JSON</label><input id="workspace-file" class="file-input" type="file" accept=".json,application/json"/></div></div></div><div class="row wrap" style="margin-top:12px"><button class="btn" data-action="export-workspace">${icon('download')} Export workspace</button><button class="btn" data-action="export-projects-csv">Export projects CSV</button><button class="btn" data-action="export-analytics-csv">Export analytics CSV</button></div></section>
    <section class="panel panel-pad"><div class="panel-title"><div><h3>Workspace inventory</h3><p>Actual และ Demo records แยกด้วย isDemo</p></div></div><div class="grid-2"><div class="metric-card"><b>${workspace.channels.length}</b><span>Channels</span></div><div class="metric-card"><b>${workspace.projects.length}</b><span>Projects</span></div><div class="metric-card"><b>${workspace.analytics.length}</b><span>Analytics entries</span></div><div class="metric-card"><b>${workspace.credits.length}</b><span>Credit records</span></div></div><div class="divider"></div><div class="inline-note">Last updated: ${escapeHtml(workspace.updatedAt)}<br/>Workspace id: ${escapeHtml(workspace.id)}</div></section>
    <section class="panel panel-pad"><div class="panel-title"><div><h3>Demo data controls</h3><p>ลบ Demo records ได้ในคลิกเดียว โดยเก็บ 50 Ideas และ Policy Registry ไว้</p></div></div><div class="inline-note warning">การลบ Demo จะนำ Channel, Projects, Calendar, Analytics และ Credit entries ที่ติดป้าย Demo ออก ไม่กระทบข้อมูลจริง</div><div class="row wrap" style="margin-top:14px"><button class="btn warning" data-action="remove-demo-data">Remove Demo Data</button><button class="btn danger" data-action="reset-workspace">Reset entire workspace</button></div></section>
    <section class="panel panel-pad"><div class="panel-title"><div><h3>Import contract</h3><p>ไฟล์ต้องผ่าน Runtime validation ก่อนแทนที่ข้อมูลปัจจุบัน</p></div></div><ul class="bullet-list"><li>schemaVersion ต้องเป็น 1</li><li>Workspace id ต้องเป็น “default”</li><li>State arrays และ Settings ต้องมีชนิดข้อมูลที่ระบบรองรับ</li><li>Import ไม่รวม API Key หรือ Secret ใด ๆ</li><li>ควร Export backup ก่อน Import ทุกครั้ง</li></ul></section>
  </div>`;
