import type { Workspace } from '../domain/types.js';
import { channelById } from '../app/selectors.js';
import { escapeHtml, formatThb } from '../domain/utils.js';
import { dataLabel, metricCard, pageHeader } from '../ui/components.js';

export const renderMonetization = (workspace: Workspace): string => {
  const estimated = workspace.monetization.reduce((sum,path) => sum + path.estimatedMonthlyThb,0);
  const confirmed = workspace.monetization.reduce((sum,path) => sum + path.confirmedMonthlyThb,0);
  const platform = workspace.monetization.filter((path) => path.type === 'platform').reduce((sum,path) => sum + path.estimatedMonthlyThb,0);
  const leads = workspace.monetization.filter((path) => path.type === 'lead-generation').reduce((sum,path) => sum + path.estimatedMonthlyThb,0);
  return `${pageHeader('Monetization Vault','ออกแบบรายได้แยก Platform, Off-platform และ Lead generation โดยไม่รอค่าโฆษณาอย่างเดียว','<a class="btn" href="#/policy">Check eligibility</a><a class="btn primary" href="#/analytics">Review actual revenue</a>')}
    <div class="grid-4" style="margin-bottom:16px">${metricCard(formatThb(estimated),'Estimated monthly','violet')}${metricCard(formatThb(confirmed),'Confirmed monthly','green')}${metricCard(formatThb(platform),'Platform estimate','cyan')}${metricCard(formatThb(leads),'Lead-generation value','amber')}</div>
    <div class="grid-3">${workspace.monetization.map((path) => { const channel = channelById(workspace,path.channelId); return `<article class="path-card"><div class="row between"><span class="chip ${path.type === 'platform' ? 'cyan' : path.type === 'lead-generation' ? 'amber' : 'violet'}">${escapeHtml(path.type)}</span>${path.confirmedMonthlyThb > 0 ? dataLabel('actual') : dataLabel('estimated')}</div><h3>${escapeHtml(path.name)}</h3><p>${escapeHtml(channel?.name ?? 'Unknown channel')} · ${escapeHtml(path.status)}</p><div class="path-values"><div class="metric-card"><b>${formatThb(path.estimatedMonthlyThb)}</b><span>Estimated</span></div><div class="metric-card"><b>${formatThb(path.confirmedMonthlyThb)}</b><span>Confirmed</span></div></div><div class="inline-note"><strong>Next action</strong><br/>${escapeHtml(path.nextAction)}</div></article>`; }).join('')}</div>
    <div class="grid-2" style="margin-top:16px"><article class="panel panel-pad"><div class="panel-title"><div><h3>เพิ่มเส้นทางรายได้</h3><p>แยกค่าประมาณออกจากรายได้ที่ยืนยันแล้ว</p></div></div><form class="stack" data-form="monetization-path"><div class="field"><label>Channel</label><select class="select" name="channelId">${workspace.channels.map((channel) => `<option value="${escapeHtml(channel.id)}">${escapeHtml(channel.name)}</option>`).join('')}</select></div><div class="field"><label>Name</label><input class="input" name="name" required placeholder="เช่น AI workflow template affiliate"/></div><div class="form-grid"><div class="field"><label>Type</label><select class="select" name="type"><option value="platform">Platform revenue</option><option value="off-platform">Off-platform</option><option value="lead-generation">Lead generation</option></select></div><div class="field"><label>Status</label><select class="select" name="status"><option value="idea">Idea</option><option value="testing">Testing</option><option value="active">Active</option><option value="paused">Paused</option></select></div></div><div class="form-grid"><div class="field"><label>Estimated / month</label><input class="input" type="number" name="estimatedMonthlyThb" min="0" value="0"/></div><div class="field"><label>Confirmed / month</label><input class="input" type="number" name="confirmedMonthlyThb" min="0" value="0"/></div></div><div class="field"><label>Next action</label><textarea class="textarea" name="nextAction" required></textarea></div><button class="btn primary" type="submit">Add monetization path</button></form></article><article class="panel panel-pad"><div class="panel-title"><div><h3>Niche monetization logic</h3><p>เลือกเส้นทางตาม Intent ของผู้ชม ไม่ใช่ตามยอดวิวอย่างเดียว</p></div></div><div class="stack"><div class="inline-note"><strong>History / Dhamma</strong><br/>เริ่มจาก Audience + Watch Time แล้วต่อยอด Sponsor, Digital product หรือ Community เมื่อมี Proof set</div><div class="inline-note"><strong>AI / Business</strong><br/>เน้น Affiliate, Templates, Audit และ Lead generation ได้ก่อนผ่าน YPP หากเนื้อหาพิสูจน์ผลลัพธ์จริง</div><div class="inline-note"><strong>Thailand / Property</strong><br/>ใช้ Video เป็น Lead engine แยกมูลค่า Lead ออกจาก Revenue บนแพลตฟอร์ม และระบุคำเตือนข้อมูลปัจจุบัน</div></div></article></div>`;
};
