import type { View } from '../app/view.js';
import { navigate } from '../app/router.js';
import { awardXp, getWorkspace, updateWorkspace } from '../app/store.js';
import { escapeHtml } from '../domain/utils.js';
import { chip, progress } from '../ui/components.js';
import { showToast } from '../ui/feedback.js';

let step=1;
let replayActive=false;

export const restartOnboardingFlow=():void=>{step=1;replayActive=true;};
export const resetOnboardingFlow=():void=>{step=1;replayActive=false;};
export const isOnboardingReplayActive=():boolean=>replayActive;

export const renderOnboarding=():View=>{
  const workspace=getWorkspace();
  const replaying=isOnboardingReplayActive();
  const stepOne=`<div class="onboarding-copy"><span class="eyebrow">Creator Empire Simulator</span><h1>สร้างระบบผลิตวิดีโอ ไม่ใช่แค่เก็บไอเดีย</h1><p>เลือก Niche สร้าง Channel Blueprint ทำ Prompt Pack คุมเครดิต CapCut วาง Calendar และเรียนรู้จาก Analytics ในระบบเดียว</p><div class="onboarding-features"><div><b>50</b><span>Seed ideas</span></div><div><b>16</b><span>Prompt workflows</span></div><div><b>17</b><span>Production stages</span></div><div><b>2</b><span>Demo channels</span></div></div><button type="button" class="btn primary large" data-onboard-next>เริ่มตั้งค่า</button></div>`;
  const stepTwo=`<form id="onboarding-settings" class="onboarding-copy"><span class="eyebrow">Step 2 of 3</span><h1>กำหนด Capacity ที่ทำได้จริง</h1><p>ระบบจะเตือนเมื่อเปิดช่อง งาน หรือเครดิตเกินเวลาที่มี แต่ไม่บล็อกการตัดสินใจของคุณ</p><div class="form-grid two"><label><span>Timezone</span><input name="timezone" value="${escapeHtml(workspace.settings.timezone)}"></label><label><span>เวลาทำช่องต่อสัปดาห์</span><input name="weeklyHours" type="number" min="1" max="100" value="${workspace.settings.weeklyHoursAvailable}"></label><label><span>CapCut credits ปัจจุบัน</span><input name="credits" type="number" min="0" value="${workspace.settings.capcutBalance}"></label><label><span>จำนวน Active channels ที่แนะนำ</span><input name="channelLimit" type="number" min="1" max="10" value="${workspace.settings.activeChannelLimit}"></label></div><div class="onboarding-actions"><button type="button" class="btn ghost" data-onboard-back>ย้อนกลับ</button><button type="submit" class="btn primary">บันทึกและไปต่อ</button></div></form>`;
  const demoChoice=replaying?`<div class="setup-replay-safety" role="note"><b>ทบทวนแบบไม่ลบข้อมูล</b><span>Channel, Video, Calendar, Analytics และ Demo Workspace ปัจจุบันจะคงเดิม</span></div>`:`<label class="switch-line onboarding-check"><span><b>เปิด Demo Workspace</b><small>ข้อมูลทุกชิ้นมีป้าย Demo ชัดเจน</small></span><input id="keep-demo" type="checkbox" checked></label>`;
  const stepThree=`<div class="onboarding-copy"><span class="eyebrow">Step 3 of 3</span><h1>เริ่มจากหนึ่งช่องหลัก + หนึ่งช่องทดลอง</h1><p>Demo Workspace เตรียม History Lab ภาษาอังกฤษ และ FlowBiz AI Minute ภาษาไทยไว้ให้ คุณลบ Demo ได้ทุกเมื่อ</p><div class="starter-channels"><article><span class="channel-avatar">HL</span><div><strong>History Lab</strong><small>Primary · EN · Strange History</small><p>ทดสอบ Shorts และขยายเรื่องชนะเป็น Long-form</p></div>${chip('Primary','cyan')}</article><article><span class="channel-avatar">AI</span><div><strong>FlowBiz AI Minute</strong><small>Experiment · TH · AI Automation</small><p>ทดสอบรายได้จาก Lead และเครื่องมือก่อนพึ่งโฆษณา</p></div>${chip('Experiment','amber')}</article></div>${demoChoice}<div class="onboarding-actions"><button type="button" class="btn ghost" data-onboard-back>ย้อนกลับ</button><button type="button" class="btn primary" data-onboard-finish>เข้า Studio HQ</button></div></div>`;
  const html=`<div class="onboarding-screen"><div class="onboarding-brand"><span class="brand-mark"></span><strong>Creator Empire</strong></div><div class="onboarding-progress">${progress(step*33.33,`Step ${step} of 3`)}</div><main class="onboarding-card">${step===1?stepOne:step===2?stepTwo:stepThree}</main><footer>Local-first · No API required · Sound off by default</footer></div>`;
  return{html,mount:()=>{document.querySelector('[data-onboard-next]')?.addEventListener('click',()=>{step=2;location.hash='#/onboarding';window.dispatchEvent(new Event('hashchange'));});document.querySelectorAll('[data-onboard-back]').forEach((element)=>element.addEventListener('click',()=>{step=Math.max(1,step-1);window.dispatchEvent(new Event('hashchange'));}));document.querySelector<HTMLFormElement>('#onboarding-settings')?.addEventListener('submit',(event)=>{event.preventDefault();const data=new FormData(event.currentTarget as HTMLFormElement);updateWorkspace((draft)=>{draft.settings.timezone=String(data.get('timezone')||'Asia/Bangkok');draft.settings.weeklyHoursAvailable=Number(data.get('weeklyHours'))||12;draft.settings.capcutBalance=Number(data.get('credits'))||0;draft.settings.activeChannelLimit=Number(data.get('channelLimit'))||2;});step=3;window.dispatchEvent(new Event('hashchange'));});document.querySelector('[data-onboard-finish]')?.addEventListener('click',()=>{const keepDemo=replaying||(document.querySelector<HTMLInputElement>('#keep-demo')?.checked??true);updateWorkspace((draft)=>{draft.settings.onboardingComplete=true;if(!keepDemo){const demoProjectIds=new Set(draft.projects.filter((item)=>item.isDemo).map((item)=>item.id));const demoChannelIds=new Set(draft.channels.filter((item)=>item.isDemo).map((item)=>item.id));draft.channels=draft.channels.filter((item)=>!item.isDemo);draft.projects=draft.projects.filter((item)=>!item.isDemo);draft.analytics=draft.analytics.filter((item)=>!item.isDemo&&!demoProjectIds.has(item.projectId));draft.calendarTasks=draft.calendarTasks.filter((item)=>!item.isDemo&&!demoProjectIds.has(item.projectId??''));draft.sources=draft.sources.filter((item)=>!demoProjectIds.has(item.projectId));draft.credits=draft.credits.filter((item)=>!item.projectId||!demoProjectIds.has(item.projectId));draft.monetization=draft.monetization.filter((item)=>!demoChannelIds.has(item.channelId));}awardXp(draft,'onboarding-complete',60,'consistency');});showToast(replaying?'ทบทวนการตั้งค่าแล้ว · ข้อมูลเดิมยังอยู่ครบ':'ตั้งค่า Studio เสร็จแล้ว');navigate('hq');});}};
};
