import type { ProjectStatus, VideoProject } from '../domain/types.js';
import type { View } from '../app/view.js';
import { getQuery, navigate, routeHref } from '../app/router.js';
import { requestRender } from '../app/runtime.js';
import { awardXp, getWorkspace, updateWorkspace } from '../app/store.js';
import { activeChannel, activeProject, statusLabels } from '../app/selectors.js';
import { applyChannelFocus, applyProjectFocus } from '../domain/focus.js';
import { buildWorkflowTasks, recordWorkflowEvent, syncNextWorkflowMission, workflowReadiness, workflowStageRank, workflowStatuses } from '../domain/workflow.js';
import { addDays, escapeHtml, todayIso, uid } from '../domain/utils.js';
import { button, chip, dataBadge, metric, pageHeader } from '../ui/components.js';
import { openDialog, showToast } from '../ui/feedback.js';

const statuses = workflowStatuses.map((id) => ({ id, label: statusLabels[id] }));
let channelFilter = '';
let languageFilter = 'all';
let formatFilter = 'all';
let compactMode = false;

const stageIndex = workflowStageRank;

const projectCard = (project: VideoProject, activeId?: string): string => {
  const workspace = getWorkspace();
  const channel = workspace.channels.find((candidate) => candidate.id === project.channelId);
  const overdue = project.deadline < todayIso() && !['published', 'archived'].includes(project.status);
  const currentTask = workspace.calendarTasks.find((task) => task.projectId === project.id && !task.completed && task.sourceStatus === project.status);
  return `<article class="kan-card ${overdue ? 'overdue' : ''} ${project.id === activeId ? 'active-project' : ''}" draggable="true" data-project-id="${escapeHtml(project.id)}" tabindex="0">
    <button type="button" class="card-open" data-action="open-project" data-id="${escapeHtml(project.id)}"><div class="card-top"><span class="channel-dot ${channel?.role ?? 'backlog'}"></span><span>${escapeHtml(channel?.name ?? 'Unassigned')}</span>${dataBadge(project.isDemo)}</div><h3>${escapeHtml(project.title)}</h3><p>${escapeHtml(currentTask?.title ?? (project.hook || project.series || 'ยังไม่มี Mission'))}</p><div class="chip-row">${chip(project.language.toUpperCase(), project.language === 'en' ? 'cyan' : 'amber')}${chip(project.format, project.format === 'shorts' ? '' : 'violet')}${project.riskLevel !== 'low' ? chip(project.riskLevel, 'amber') : ''}</div><div class="card-footer"><span>${overdue ? 'Overdue' : `Due ${project.deadline}`}</span><span>${project.actualCredits || `${project.creditEstimateLow}–${project.creditEstimateHigh}`} cr</span></div></button>
  </article>`;
};

const projectDialog = (project: VideoProject): void => {
  const workspace = getWorkspace();
  const channel = workspace.channels.find((candidate) => candidate.id === project.channelId);
  const body = `<form id="project-editor" class="project-editor"><div class="summary-grid">${metric('Channel', channel?.name ?? 'Unassigned')}${metric('Status', statusLabels[project.status])}${metric('Language', project.language.toUpperCase())}${metric('Credits', project.actualCredits || `${project.creditEstimateLow}–${project.creditEstimateHigh}`)}</div><div class="form-grid two"><label><span>Title</span><input name="title" value="${escapeHtml(project.title)}" required></label><label><span>Deadline</span><input name="deadline" type="date" value="${escapeHtml(project.deadline)}" required></label><label><span>Owner</span><input name="owner" value="${escapeHtml(project.owner)}"></label><label><span>Estimate minutes</span><input name="estimatedMinutes" type="number" min="1" value="${project.estimatedMinutes}"></label><label><span>Budget THB</span><input name="budgetThb" type="number" min="0" value="${project.budgetThb}"></label><label><span>Current stage</span><input value="${escapeHtml(statusLabels[project.status])}" disabled></label></div><label><span>Research summary</span><textarea name="researchSummary" rows="3">${escapeHtml(project.researchSummary)}</textarea></label><label><span>Fact-check summary</span><textarea name="factCheckSummary" rows="3">${escapeHtml(project.factCheckSummary)}</textarea></label><label><span>Hook</span><textarea name="hook" rows="3">${escapeHtml(project.hook)}</textarea></label><label><span>Script</span><textarea name="script" rows="7">${escapeHtml(project.script)}</textarea></label><label><span>Lessons learned</span><textarea name="lessons" rows="3">${escapeHtml(project.lessonsLearned)}</textarea></label><div class="project-links"><button type="button" class="btn primary" data-action="project-mission">Mission Control</button><button type="button" class="btn ghost" data-action="project-prompt">Prompt Studio</button><button type="button" class="btn ghost" data-action="project-capcut">CapCut Lab</button><button type="button" class="btn ghost" data-action="project-calendar">Calendar</button><button type="button" class="btn ghost" data-action="project-policy">Policy</button></div><div class="dialog-actions"><button type="button" class="btn danger" data-action="archive-project">Archive</button><button type="submit" class="btn primary">Save project</button></div></form>`;
  const dialog = openDialog(project.title, body, 'xl');
  dialog.querySelector<HTMLFormElement>('#project-editor')?.addEventListener('submit', (event) => {
    event.preventDefault();
    const data = new FormData(event.currentTarget as HTMLFormElement);
    updateWorkspace((draft) => {
      const target = draft.projects.find((candidate) => candidate.id === project.id);
      if (!target) return;
      target.title = String(data.get('title') ?? '').trim(); target.deadline = String(data.get('deadline') ?? target.deadline); target.owner = String(data.get('owner') ?? target.owner).trim(); target.estimatedMinutes = Number(data.get('estimatedMinutes')) || target.estimatedMinutes; target.budgetThb = Number(data.get('budgetThb')) || 0; target.researchSummary = String(data.get('researchSummary') ?? '').trim(); target.factCheckSummary = String(data.get('factCheckSummary') ?? '').trim(); target.hook = String(data.get('hook') ?? '').trim(); target.script = String(data.get('script') ?? '').trim(); target.lessonsLearned = String(data.get('lessons') ?? '').trim(); target.updatedAt = new Date().toISOString(); applyProjectFocus(draft, target.id);
    });
    dialog.close(); showToast('บันทึก Project แล้ว');
  });
  dialog.querySelector('[data-action="archive-project"]')?.addEventListener('click', () => { updateWorkspace((draft) => { const target = draft.projects.find((candidate) => candidate.id === project.id); if (target) { target.status = 'archived'; syncNextWorkflowMission(draft, target.id); } }); dialog.close(); });
  const go = (action: string, route: string) => dialog.querySelector(`[data-action="${action}"]`)?.addEventListener('click', () => { dialog.close(); updateWorkspace((draft) => applyProjectFocus(draft, project.id)); navigate(route, { project: project.id }); });
  go('project-mission', 'mission'); go('project-prompt', 'prompts'); go('project-capcut', 'capcut'); go('project-calendar', 'calendar'); go('project-policy', 'policy');
};

const newProjectDialog = (): void => {
  const workspace = getWorkspace();
  const channel = activeChannel(workspace) ?? workspace.channels[0];
  const body = `<form id="new-project-form"><div class="form-grid two"><label><span>Title</span><input name="title" required placeholder="New video title"></label><label><span>Channel</span><select name="channelId" required>${workspace.channels.map((item) => `<option value="${item.id}" ${item.id === channel?.id ? 'selected' : ''}>${escapeHtml(item.name)}</option>`).join('')}</select></label><label><span>Language</span><select name="language"><option value="en">English</option><option value="th">ไทย</option></select></label><label><span>Format</span><select name="format"><option value="shorts">Shorts</option><option value="long">Long-form</option></select></label><label><span>Deadline</span><input name="deadline" type="date" value="${addDays(todayIso(), 5)}"></label><label><span>Target duration (sec)</span><input name="duration" type="number" value="55" min="10"></label></div><label><span>Series</span><input name="series" placeholder="Series name"></label><div class="dialog-actions"><button type="submit" class="btn primary">Create project and workflow</button></div></form>`;
  const dialog = openDialog('Add video project', body, 'md');
  dialog.querySelector<HTMLFormElement>('#new-project-form')?.addEventListener('submit', (event) => {
    event.preventDefault();
    const data = new FormData(event.currentTarget as HTMLFormElement); const channelId = String(data.get('channelId')); const ownerChannel = workspace.channels.find((candidate) => candidate.id === channelId)!; const idea = workspace.ideas.find((candidate) => candidate.id === ownerChannel.ideaId); const format = String(data.get('format')) as 'shorts' | 'long'; const now = new Date().toISOString();
    const project: VideoProject = { id: uid('project'), title: String(data.get('title')).trim(), channelId, ideaId: ownerChannel.ideaId, series: String(data.get('series') ?? '').trim(), language: String(data.get('language')) as 'en' | 'th', platforms: format === 'shorts' ? ['YouTube Shorts'] : ['YouTube'], format, targetDurationSeconds: Number(data.get('duration')) || (format === 'shorts' ? 55 : 480), deadline: String(data.get('deadline')), owner: 'Nat', estimatedMinutes: idea?.score[ownerChannel.language].productionMinutes ?? 120, budgetThb: 0, creditEstimateLow: idea?.score[ownerChannel.language].estimatedCreditsLow ?? 40, creditEstimateHigh: idea?.score[ownerChannel.language].estimatedCreditsHigh ?? 120, actualCredits: 0, status: 'selected', sourceIds: [], researchSummary: '', factCheckSummary: '', scriptVersion: 0, script: '', hook: '', storyboard: [], assetPrompts: [], capcutBrief: '', promptVersions: [], thumbnailVersions: [], publicationLinks: [], lessonsLearned: '', analyticsPostmortem: '', repurposingPlan: '', workflowEvents: [], policyChecks: {}, riskLevel: idea?.score[ownerChannel.language].copyrightRisk ?? 'review', createdAt: now, updatedAt: now };
    updateWorkspace((draft) => { draft.projects.push(project); const tasks = buildWorkflowTasks(draft, project); draft.calendarTasks.push(...tasks); applyProjectFocus(draft, project.id, tasks[0]?.id); awardXp(draft, `project-created:${project.id}`, 35, 'topicSelection'); }); dialog.close(); showToast('สร้าง Project และ Workflow missions แล้ว'); navigate('mission', { project: project.id });
  });
};

export const renderPipeline = (): View => {
  const workspace = getWorkspace();
  const focusedChannel = activeChannel(workspace);
  const focusedProject = activeProject(workspace);
  const effectiveChannel = channelFilter || (workspace.focus.mode === 'channel' ? focusedChannel?.id ?? 'all' : 'all');
  const requestedProject = getQuery().get('project');
  const projects = workspace.projects.filter((project) => (effectiveChannel === 'all' || project.channelId === effectiveChannel) && (languageFilter === 'all' || project.language === languageFilter) && (formatFilter === 'all' || project.format === formatFilter));
  const wip = projects.filter((project) => ['researching', 'sources-verified', 'hook-ready', 'script-draft', 'script-approved', 'storyboard', 'assets-needed', 'capcut-draft', 'editing', 'qa'].includes(project.status)).length;
  const columns = statuses.map((status) => { const cards = projects.filter((project) => project.status === status.id); return `<section class="kan-column ${compactMode ? 'compact' : ''}" data-status="${status.id}"><div class="kan-column-head"><span>${escapeHtml(status.label)}</span><b>${cards.length}</b></div><div class="kan-dropzone" data-drop-status="${status.id}">${cards.map((item) => projectCard(item, focusedProject?.id)).join('') || '<div class="kan-empty">Drop here</div>'}</div></section>`; }).join('');
  const html = `${pageHeader('Production Pipeline', 'Pipeline เป็นตัวกำหนด Mission และ Prompt ถัดไป; การเลื่อนไปข้างหน้าต้องผ่าน Completion Gate', `${button('Add video project', 'add-project', 'primary', 'plus')}${button(compactMode ? 'Comfort view' : 'Compact view', 'toggle-compact', 'ghost')}<a class="btn" href="${routeHref('mission', focusedProject ? { project: focusedProject.id } : undefined)}">Mission Control</a>`)}<section class="hq-focus-strip pipeline-focus-strip"><div><span class="kicker">Channel Focus</span><h3>${escapeHtml(focusedChannel?.name ?? 'Portfolio')}</h3><p>${effectiveChannel === 'all' ? 'All channels visible' : 'Board scoped to one channel'}</p></div><div><span class="kicker">Active Project</span><h3>${escapeHtml(focusedProject?.title ?? 'None')}</h3><p>${focusedProject ? statusLabels[focusedProject.status] : 'Select a card'}</p></div><div class="focus-strip-actions"><button class="btn" data-action="open-focus-picker">Change focus</button></div></section><div class="pipeline-toolbar panel"><div class="pipeline-filters"><label><span>Channel</span><select id="pipeline-channel"><option value="all">Portfolio · all channels</option>${workspace.channels.map((item) => `<option value="${item.id}" ${effectiveChannel === item.id ? 'selected' : ''}>${escapeHtml(item.name)}</option>`).join('')}</select></label><label><span>Language</span><select id="pipeline-language"><option value="all">All</option><option value="en" ${languageFilter === 'en' ? 'selected' : ''}>EN</option><option value="th" ${languageFilter === 'th' ? 'selected' : ''}>TH</option></select></label><label><span>Format</span><select id="pipeline-format"><option value="all">All</option><option value="shorts" ${formatFilter === 'shorts' ? 'selected' : ''}>Shorts</option><option value="long" ${formatFilter === 'long' ? 'selected' : ''}>Long-form</option></select></label></div><div class="wip-meter"><span>WIP Limit</span><strong class="${wip > 8 ? 'risk' : ''}">${wip} / 8</strong><div class="mini-track"><i style="width:${Math.min(100, (wip / 8) * 100)}%"></i></div><small>${wip >= 8 ? 'ปิดงานก่อนเปิดเพิ่ม' : 'Capacity available'}</small></div><div class="pipeline-summary">${metric('Visible', projects.length)}${metric('Overdue', projects.filter((item) => item.deadline < todayIso() && !['published', 'archived'].includes(item.status)).length)}${metric('Review risk', projects.filter((item) => item.riskLevel !== 'low').length)}</div></div><div class="kanban-board" aria-label="Production stages">${columns}</div>`;
  return { html, mount: () => {
    const moveProject = (projectId: string, nextStatus: ProjectStatus): void => {
      const currentWorkspace = getWorkspace(); const project = currentWorkspace.projects.find((item) => item.id === projectId); if (!project || project.status === nextStatus) return; const currentIndex = stageIndex(project.status); const nextIndex = stageIndex(nextStatus);
      if (nextIndex > currentIndex) {
        const expected = workflowStatuses[currentIndex + 1]; const readiness = workflowReadiness(currentWorkspace, project, expected);
        if (nextStatus !== expected || !readiness.ready) { updateWorkspace((draft) => applyProjectFocus(draft, project.id)); showToast(readiness.blockers[0] ?? 'ทำ Mission ของขั้นนี้ก่อนเลื่อน Pipeline', 'warning'); navigate('mission', { project: project.id }); return; }
      }
      updateWorkspace((draft) => { const target = draft.projects.find((item) => item.id === projectId); if (!target) return; const previous = target.status; target.status = nextStatus; target.updatedAt = new Date().toISOString(); recordWorkflowEvent(target, { type: 'stage-advanced', note: `Pipeline moved to ${statusLabels[nextStatus]}`, fromStatus: previous, toStatus: nextStatus }); syncNextWorkflowMission(draft, target.id); applyProjectFocus(draft, target.id, draft.calendarTasks.find((task) => task.projectId === target.id && !task.completed && task.sourceStatus === target.status)?.id); awardXp(draft, `stage:${target.id}:${nextStatus}`, 35, 'consistency'); }); showToast(`ย้ายไป ${statusLabels[nextStatus]}`);
    };
    const setFilter = (id: string, setter: (value: string) => void) => document.querySelector<HTMLSelectElement>(id)?.addEventListener('change', (event) => { setter((event.currentTarget as HTMLSelectElement).value); requestRender(); });
    setFilter('#pipeline-channel', (value) => { channelFilter = value; updateWorkspace((draft) => { if (value === 'all') draft.focus.mode = 'portfolio'; else applyChannelFocus(draft, value); }); }); setFilter('#pipeline-language', (value) => { languageFilter = value; }); setFilter('#pipeline-format', (value) => { formatFilter = value; });
    document.querySelector('[data-action="add-project"]')?.addEventListener('click', newProjectDialog); document.querySelector('[data-action="toggle-compact"]')?.addEventListener('click', () => { compactMode = !compactMode; requestRender(); }); document.querySelectorAll<HTMLElement>('[data-action="open-project"]').forEach((element) => element.addEventListener('click', () => { const project = workspace.projects.find((candidate) => candidate.id === element.dataset.id); if (project) { updateWorkspace((draft) => applyProjectFocus(draft, project.id)); projectDialog(project); } }));
    let draggedId = ''; document.querySelectorAll<HTMLElement>('[draggable="true"]').forEach((card) => { card.addEventListener('dragstart', (event) => { draggedId = card.dataset.projectId ?? ''; card.classList.add('dragging'); event.dataTransfer?.setData('text/plain', draggedId); }); card.addEventListener('dragend', () => card.classList.remove('dragging')); card.addEventListener('keydown', (event) => { if (!['ArrowRight', 'ArrowLeft'].includes(event.key)) return; event.preventDefault(); const project = workspace.projects.find((candidate) => candidate.id === card.dataset.projectId); if (!project) return; const index = Math.max(0, Math.min(statuses.length - 1, stageIndex(project.status) + (event.key === 'ArrowRight' ? 1 : -1))); moveProject(project.id, statuses[index].id); }); });
    document.querySelectorAll<HTMLElement>('[data-drop-status]').forEach((zone) => { zone.addEventListener('dragover', (event) => { event.preventDefault(); zone.classList.add('drag-over'); }); zone.addEventListener('dragleave', () => zone.classList.remove('drag-over')); zone.addEventListener('drop', (event) => { event.preventDefault(); zone.classList.remove('drag-over'); moveProject(event.dataTransfer?.getData('text/plain') || draggedId, zone.dataset.dropStatus as ProjectStatus); }); });
    if (requestedProject) { const project = workspace.projects.find((candidate) => candidate.id === requestedProject); if (project) window.setTimeout(() => projectDialog(project), 50); }
  } };
};
