import type { Workspace } from '../domain/types.js';
import { activeProject, projectsInFocus, projectById, statusLabels } from '../app/selectors.js';
import { routeHref } from '../app/router.js';
import { escapeHtml } from '../domain/utils.js';
import { policyRiskLevel, requiredPolicyChecks, workflowReadiness } from '../domain/workflow.js';
import { chip, pageHeader, riskChip } from '../ui/components.js';

const checks = [
  ['originalScript', 'Script เป็นงานต้นฉบับและไม่คัดลอกโครงประโยคจากแหล่งเดียว'],
  ['sourcesPresent', 'มีแหล่งข้อมูลที่เพียงพอและตรวจวันเข้าถึงแล้ว'],
  ['claimsClassified', 'แยก Documented, Reported, Disputed และ Unsupported claims'],
  ['aiDisclosureReviewed', 'ตรวจว่าต้องเปิดเผย realistic AI reconstruction หรือไม่'],
  ['musicLicensed', 'เพลง เสียง และ Footage มีสิทธิ์ใช้งาน'],
  ['templateRiskReviewed', 'ตรวจความเสี่ยง Template ซ้ำและความแตกต่างจากคลิปก่อน'],
  ['sensitiveContentReviewed', 'ตรวจบุคคลจริง เหตุการณ์รุนแรง สุขภาพ การเงิน หรือกฎหมาย'],
  ['trademarkReviewed', 'ตรวจ Logo, Trademark, Product claim และภาพบรรจุภัณฑ์'],
] as const;

export const renderPolicy = (workspace: Workspace, params: URLSearchParams): string => {
  const project = projectById(workspace, params.get('project') ?? undefined) ?? activeProject(workspace) ?? workspace.projects[0];
  const scopedProjects = projectsInFocus(workspace);
  const mandatoryMissing = project ? requiredPolicyChecks.filter((key) => !project.policyChecks[key]) : [...requiredPolicyChecks];
  const optionalCompleted = project ? checks.filter(([key]) => !requiredPolicyChecks.includes(key as typeof requiredPolicyChecks[number]) && project.policyChecks[key]).length : 0;
  const derivedRisk = project ? policyRiskLevel(project) : 'review';
  const readiness = project ? workflowReadiness(workspace, project, 'scheduled') : { ready: false, completed: [], blockers: [] };
  return `${pageHeader('Policy Shield', 'Contextual release gate: Mandatory checks ต้องผ่านครบก่อน QA → Scheduled', `${project ? `<a class="btn" href="${routeHref('mission', { project: project.id })}">Back to mission</a><a class="btn primary" href="${routeHref('prompts', { project: project.id, type: 'fact-check' })}">Fact-check</a>` : ''}`)}
    ${project ? `<section class="policy-mission-strip"><div><span class="kicker">Release gate</span><h3>${escapeHtml(project.title)}</h3><p>${escapeHtml(statusLabels[project.status])} · ${mandatoryMissing.length ? `${mandatoryMissing.length} mandatory blocker(s)` : 'Mandatory checks complete'}</p></div><div class="row wrap">${riskChip(derivedRisk)}${chip(`${requiredPolicyChecks.length - mandatoryMissing.length}/${requiredPolicyChecks.length} mandatory`, mandatoryMissing.length ? 'amber' : 'green')}<button class="btn ${readiness.ready ? 'primary' : ''}" data-action="complete-mission" data-project-id="${escapeHtml(project.id)}">Complete & advance</button></div></section>` : ''}
    <div class="grid-2">
      <section class="panel panel-pad"><div class="panel-title"><div><h3>Release checklist</h3><p>Mandatory ต้อง 100%; Optional ใช้เมื่อเนื้อหาเกี่ยวข้อง</p></div>${riskChip(derivedRisk)}</div><div class="field" style="margin-bottom:13px"><label>Video</label><select class="select" data-change="policy-project">${scopedProjects.map((item) => `<option value="${escapeHtml(item.id)}" ${item.id === project?.id ? 'selected' : ''}>${escapeHtml(item.title)}</option>`).join('')}</select></div><div class="inline-note ${derivedRisk === 'high' ? 'danger' : derivedRisk === 'review' ? 'warning' : 'success'}"><strong>${mandatoryMissing.length ? 'Release blocked' : 'Mandatory release checks complete'}</strong><br/>${mandatoryMissing.length ? `Missing: ${escapeHtml(mandatoryMissing.join(', '))}` : `${optionalCompleted} optional check(s) also completed.`}</div><div class="checklist" style="margin-top:14px">${project ? checks.map(([key, label]) => { const mandatory = requiredPolicyChecks.includes(key as typeof requiredPolicyChecks[number]); return `<label class="check-item"><input type="checkbox" data-change="policy-check" data-project-id="${escapeHtml(project.id)}" data-check-key="${escapeHtml(key)}" ${project.policyChecks[key] ? 'checked' : ''}/><span><strong>${mandatory ? 'Required' : 'Conditional'}</strong> · ${escapeHtml(label)}</span></label>`; }).join('') : ''}</div>${project ? `<div class="field" style="margin-top:14px"><label>AI disclosure review evidence</label><textarea class="textarea" rows="3" data-change="policy-evidence" data-project-id="${escapeHtml(project.id)}" data-evidence-key="aiDisclosureReviewed" placeholder="Record whether realistic synthetic media is present and where the disclosure appears, or why none is required.">${escapeHtml(project.policyEvidence?.aiDisclosureReviewed ?? '')}</textarea></div><div class="field" style="margin-top:14px"><label>Music and footage rights evidence</label><textarea class="textarea" rows="3" data-change="policy-evidence" data-project-id="${escapeHtml(project.id)}" data-evidence-key="musicLicensed" placeholder="Record the license, source, asset IDs, or public-domain basis.">${escapeHtml(project.policyEvidence?.musicLicensed ?? '')}</textarea></div><div class="field" style="margin-top:14px"><label>Template differentiation evidence</label><textarea class="textarea" rows="3" data-change="policy-evidence" data-project-id="${escapeHtml(project.id)}" data-evidence-key="templateRiskReviewed" placeholder="Record the compared videos and the distinct hook, structure, visuals, or narration choices.">${escapeHtml(project.policyEvidence?.templateRiskReviewed ?? '')}</textarea></div><div class="row wrap" style="margin-top:14px"><button class="btn primary" data-action="recalculate-risk" data-project-id="${escapeHtml(project.id)}">Recalculate release risk</button></div>` : ''}</section>
      <aside class="stack"><section class="panel panel-pad"><div class="panel-title"><div><h3>Completion gate</h3><p>สิ่งที่ระบบตรวจได้จาก Active Video</p></div>${readiness.ready ? chip('Ready','green') : chip('Blocked','amber')}</div><h4>Passed</h4><ul class="bullet-list">${readiness.completed.map((item) => `<li>${escapeHtml(item)}</li>`).join('') || '<li>ยังไม่มี</li>'}</ul><div class="divider"></div><h4>Blockers</h4><ul class="bullet-list">${readiness.blockers.map((item) => `<li>${escapeHtml(item)}</li>`).join('') || '<li>ไม่มี Blocker</li>'}</ul></section><section class="panel panel-pad"><h3>Policy Registry</h3><p class="muted small-copy">ข้อมูลเปลี่ยนแปลงได้จึงเก็บ Source และ Last verified date</p>${workspace.policies.slice(0,8).map((rule) => `<article class="policy-rule"><div><strong>${escapeHtml(rule.topic)}</strong><span>${escapeHtml(rule.platform)} · ${escapeHtml(rule.country)}</span></div><em>${escapeHtml(rule.lastVerifiedAt)}</em><p>${escapeHtml(rule.summary)}</p></article>`).join('')}</section></aside>
    </div>`;
};
