import type { Workspace } from '../domain/types.js';
import { escapeHtml } from '../domain/utils.js';
import { pageHeader, progress } from '../ui/components.js';
import { aiWorkflowCoverage } from '../domain/ai-contracts.js';

const n = (value: number | undefined, fallback: number): number => Number.isFinite(value) ? Number(value) : fallback;

export const renderSettings = (workspace: Workspace): string => `${pageHeader('Settings','ตั้งค่า Workflow, AI budget, เวลาทำงาน และ Local Data โดยซ่อนความซับซ้อนที่ไม่จำเป็น','<button class="btn primary" data-action="save-settings">Save settings</button>')}
  <div class="settings-simple-layout">
    <section class="stack">
      <article class="panel settings-section">
        <div class="panel-title"><div><h3>Workflow</h3><p>Manual ไม่เสีย API เพิ่ม · AI Assisted ให้ระบบเรียก OpenAI/Gemini เมื่อคุณกด Generate</p></div><span class="chip ${workspace.settings.workflowMode === 'automatic' ? 'green':'cyan'}">${workspace.settings.workflowMode === 'automatic' ? 'AI Assisted':'Manual'}</span></div>
        <form id="settings-form" class="stack" data-form="settings">
          <div class="segmented-control">
            <label><input type="radio" name="workflowMode" value="manual" ${workspace.settings.workflowMode === 'manual' ? 'checked':''}/><span>Manual<br/><small>Copy Prompt ไปใช้เอง</small></span></label>
            <label><input type="radio" name="workflowMode" value="automatic" ${workspace.settings.workflowMode === 'automatic' ? 'checked':''}/><span>AI Assisted<br/><small>Generate ผ่าน Local Server</small></span></label>
          </div>
          <div class="form-grid"><div class="field"><label>Default AI provider</label><select class="select" name="aiProvider"><option value="openai" ${workspace.settings.aiProvider === 'openai' ? 'selected':''}>OpenAI</option><option value="gemini" ${workspace.settings.aiProvider === 'gemini' ? 'selected':''}>Gemini</option></select></div><div class="field"><label>UI language</label><select class="select" name="locale"><option value="th" ${workspace.settings.locale === 'th' ? 'selected':''}>ไทย</option><option value="en" ${workspace.settings.locale === 'en' ? 'selected':''}>English</option></select></div></div>
          <div class="form-grid cols-3"><div class="field"><label>OpenAI model</label><input class="input" name="openAiModel" value="${escapeHtml(workspace.settings.openAiModel)}"/></div><div class="field"><label>Gemini model</label><input class="input" name="geminiModel" value="${escapeHtml(workspace.settings.geminiModel)}"/></div><div class="field"><label>Gemini thinking</label><select class="select" name="geminiThinkingLevel">${['minimal','low','medium','high'].map((level) => `<option value="${level}" ${workspace.settings.geminiThinkingLevel === level ? 'selected':''}>${level}</option>`).join('')}</select></div></div>
          <div class="divider"></div>
          <div class="panel-title"><div><h3>Calendar capacity</h3><p>Planner ใช้เวลาว่างจริงเพื่อกระจาย Research / Script / Edit / Upload</p></div></div>
          <div class="form-grid cols-3"><div class="field"><label>Weekly hours</label><input class="input" type="number" name="weeklyHoursAvailable" min="1" max="100" value="${workspace.settings.weeklyHoursAvailable}"/></div><div class="field"><label>Workday start</label><input class="input" type="time" name="workdayStart" value="${escapeHtml(workspace.settings.workdayStart || '09:00')}"/></div><div class="field"><label>Workday end</label><input class="input" type="time" name="workdayEnd" value="${escapeHtml(workspace.settings.workdayEnd || '18:00')}"/></div></div>
          <div class="form-grid cols-3"><div class="field"><label>Default publish time</label><input class="input" type="time" name="defaultPublishTime" value="${escapeHtml(workspace.settings.defaultPublishTime || '19:00')}"/></div><div class="field"><label>Active channel limit</label><input class="input" type="number" name="activeChannelLimit" min="1" max="20" value="${workspace.settings.activeChannelLimit}"/></div><div class="field"><label>CapCut credits</label><input class="input" type="number" name="capcutBalance" min="0" value="${workspace.settings.capcutBalance}"/></div></div>
          <div class="divider"></div>
          <div class="panel-title"><div><h3>AI guardrails</h3><p>Server บังคับ Output limit, Timeout และ Budget แม้ Browser จะส่งค่ามากกว่า</p></div></div>
          <div class="form-grid cols-3"><div class="field"><label>Max output tokens</label><input class="input" type="number" name="aiMaxOutputTokens" min="128" max="16000" value="${n(workspace.settings.aiMaxOutputTokens,2500)}"/></div><div class="field"><label>Timeout seconds</label><input class="input" type="number" name="aiRequestTimeoutSeconds" min="10" max="180" value="${n(workspace.settings.aiRequestTimeoutSeconds,60)}"/></div><div class="field"><label>Daily budget USD</label><input class="input" type="number" step="0.1" min="0" name="aiDailyBudgetUsd" value="${n(workspace.settings.aiDailyBudgetUsd,2)}"/></div></div>
          <div class="form-grid cols-3"><div class="field"><label>Monthly budget USD</label><input class="input" type="number" step="0.1" min="0" name="aiMonthlyBudgetUsd" value="${n(workspace.settings.aiMonthlyBudgetUsd,20)}"/></div><div class="field"><label>OpenAI input $/1M</label><input class="input" type="number" step="0.01" min="0" name="openAiInputUsdPer1M" value="${n(workspace.settings.openAiInputUsdPer1M,0)}"/></div><div class="field"><label>OpenAI output $/1M</label><input class="input" type="number" step="0.01" min="0" name="openAiOutputUsdPer1M" value="${n(workspace.settings.openAiOutputUsdPer1M,0)}"/></div></div>
          <div class="form-grid cols-3"><div class="field"><label>Gemini input $/1M</label><input class="input" type="number" step="0.01" min="0" name="geminiInputUsdPer1M" value="${n(workspace.settings.geminiInputUsdPer1M,0)}"/></div><div class="field"><label>Gemini output $/1M</label><input class="input" type="number" step="0.01" min="0" name="geminiOutputUsdPer1M" value="${n(workspace.settings.geminiOutputUsdPer1M,0)}"/></div><div class="field"><label>Google Search $/query</label><input class="input" type="number" step="0.001" min="0" name="geminiSearchUsdPerQuery" value="${n(workspace.settings.geminiSearchUsdPerQuery,0.014)}"/></div></div>
          <div class="form-grid"><div class="field"><label>Timezone</label><input class="input" name="timezone" value="${escapeHtml(workspace.settings.timezone)}"/></div><label class="checkbox-row"><input type="checkbox" name="reducedMotion" ${workspace.settings.reducedMotion ? 'checked':''}/><span><strong>Reduced motion</strong><br/>ลด animation</span></label></div>
          <button class="btn primary" type="submit">Save settings</button>
        </form>
      </article>

      <article class="panel settings-section">
        <div class="panel-title"><div><h3>AI credentials</h3><p>คีย์ไม่ถูกบันทึกลง SQLite อีกต่อไป</p></div><button class="btn" data-action="refresh-ai-status">Refresh</button></div>
        <div class="ai-coverage-summary" aria-label="AI workflow coverage"><strong>${aiWorkflowCoverage.persistedContracts}/${aiWorkflowCoverage.promptTypes}</strong><span>Prompt workflows have structured validation and a persisted destination</span></div>
        <div class="inline-note success"><strong>แนะนำสำหรับใช้งานประจำ</strong><br/>ตั้ง OPENAI_API_KEY หรือ GEMINI_API_KEY เป็น Environment Variable ก่อนเปิดแอป ระบบจะอ่านโดยไม่ส่งค่ากลับ Browser</div>
        <div id="ai-secret-status" class="secret-status">กด Refresh เพื่อดูสถานะ</div>
        <form class="stack" data-form="ai-secret"><div class="field"><label>Provider</label><select class="select" name="provider"><option value="openai">OpenAI</option><option value="gemini">Gemini</option></select></div><div class="field"><label>Session-only API key</label><input class="input" type="password" name="apiKey" autocomplete="off" placeholder="เก็บใน memory จนกว่าจะปิด Local Server"/></div><div class="row wrap"><button class="btn primary" type="submit">Use for this session</button><button class="btn" type="button" data-action="test-ai-provider">Test provider</button><button class="btn danger" type="button" data-action="clear-ai-key">Clear session key</button></div></form>
      </article>
    </section>
    <aside class="stack">
      <article class="panel settings-section"><div class="panel-title"><div><h3>Data safety</h3><p>SQLite เป็น durable store และ IndexedDB เป็น offline mirror</p></div></div><div class="data-proof-list"><div><b>Workspace revision</b><span>${workspace.revision ?? 0}</span></div><div><b>SQLite</b><span>transactional + history</span></div><div><b>Browser mirror</b><span>reconciles on reconnect</span></div><div><b>Secrets</b><span>environment / session memory only</span></div></div></article>
      <article class="panel settings-section"><div class="panel-title"><div><h3>Skill tree</h3><p>Progress from productive events</p></div></div><div class="stack tight">${Object.entries(workspace.skills).slice(0,8).map(([key,value]) => `<div class="skill-line"><span>${escapeHtml(key.replace(/[A-Z]/g,m=>` ${m}`).trim())}</span>${progress(value,key)}<b>${value}</b></div>`).join('')}</div></article>
    </aside>
  </div>`;
