import type {
  Achievement,
  AnalyticsEntry,
  CalendarTask,
  Channel,
  CreditEntry,
  MonetizationPath,
  SkillProgress,
  VideoProject,
  Workspace,
} from '../domain/types.js';
import { generateBlueprint } from '../domain/blueprint.js';
import { addDays, todayIso } from '../domain/utils.js';
import { seedIdeas } from './ideas.js';
import { seedPolicies } from './policies.js';

const today = todayIso();
const now = new Date().toISOString();

const historyIdea = seedIdeas.find((idea) => idea.id === 'history-1')!;
const aiIdea = seedIdeas.find((idea) => idea.id === 'ai-2')!;

const historyChannel: Channel = {
  id: 'channel_history_lab',
  name: 'History Lab',
  handle: '@historylab',
  ideaId: historyIdea.id,
  niche: historyIdea.titleEn,
  language: 'en',
  role: 'primary',
  health: 82,
  weeklyHours: 7,
  weeklyShortsTarget: 4,
  monthlyLongTarget: 2,
  audienceCountries: ['United States', 'United Kingdom', 'Canada', 'Australia'],
  blueprint: generateBlueprint(historyIdea, 'en', 'both'),
  createdAt: now,
  isDemo: true,
};

const aiChannel: Channel = {
  id: 'channel_flowbiz_ai',
  name: 'FlowBiz AI Minute',
  handle: '@flowbizaith',
  ideaId: aiIdea.id,
  niche: aiIdea.titleTh,
  language: 'th',
  role: 'experiment',
  health: 64,
  weeklyHours: 3,
  weeklyShortsTarget: 3,
  monthlyLongTarget: 1,
  audienceCountries: ['Thailand'],
  blueprint: generateBlueprint(aiIdea, 'th', 'both'),
  createdAt: now,
  isDemo: true,
};

const demoProjects: VideoProject[] = [
  {
    id: 'project_wojtek_short',
    title: 'Wojtek: The Soldier Bear',
    channelId: historyChannel.id,
    ideaId: historyIdea.id,
    series: 'Animals That Changed History',
    language: 'en',
    platforms: ['YouTube Shorts', 'TikTok', 'Facebook Reels'],
    format: 'shorts',
    targetDurationSeconds: 55,
    deadline: today,
    owner: 'Nat',
    estimatedMinutes: 145,
    budgetThb: 120,
    creditEstimateLow: 70,
    creditEstimateHigh: 150,
    actualCredits: 0,
    status: 'script-approved',
    sourceIds: ['source_wojtek_iwm', 'source_wojtek_museum'],
    researchSummary: 'Authoritative museum records document Wojtek’s association with Polish soldiers, his wartime journey and later life in Edinburgh. Retellings about ammunition handling need careful wording.',
    factCheckSummary: 'Formal enlistment and unit-emblem context are safe. Use “according to accounts” for ammunition-carrying details and label visuals as reconstruction.',
    scriptVersion: 2,
    hook: 'This bear was not just a mascot—he was formally enlisted so he could travel with Polish soldiers.',
    script: 'This bear was not just a mascot. Wojtek travelled with Polish soldiers during the Second World War. Accounts connect him with the Italian campaign and Monte Cassino, but details about carrying ammunition are told differently across sources. What is documented is that the unit adopted a bear carrying a shell as its emblem. Wojtek survived the war and later lived in Edinburgh Zoo—becoming a symbol of the soldiers who had lost their home but not their identity.',
    storyboard: [
      '0–3s: close portrait of Wojtek beside Polish soldiers; title contradiction.',
      '3–10s: map from the Middle East toward Italy; introduce the unit.',
      '10–22s: camp life reconstruction; clarify formal enlistment context.',
      '22–36s: Monte Cassino landscape; distinguish documented facts from reported accounts.',
      '36–47s: emblem of a bear carrying a shell; explain legacy.',
      '47–55s: Edinburgh Zoo and final emotional payoff.',
    ],
    assetPrompts: [],
    capcutBrief: '',
    promptVersions: [],
    thumbnailVersions: ['A bear silhouette beside soldiers; text: “A Real Soldier?”'],
    publicationLinks: [],
    lessonsLearned: '',
    analyticsPostmortem: '',
    repurposingPlan: '',
    workflowEvents: [],
    policyChecks: {
      originalScript: true,
      sourcesPresent: true,
      claimsClassified: true,
      aiDisclosureReviewed: false,
      musicLicensed: false,
      templateRiskReviewed: true,
    },
    riskLevel: 'review',
    createdAt: now,
    updatedAt: now,
    isDemo: true,
  },
  {
    id: 'project_ai_boring_task',
    title: 'Automate One Boring Task: Lead Follow-up',
    channelId: aiChannel.id,
    ideaId: aiIdea.id,
    series: 'งานนี้ให้ออโต',
    language: 'th',
    platforms: ['YouTube Shorts', 'Facebook Reels'],
    format: 'shorts',
    targetDurationSeconds: 50,
    deadline: addDays(today, 1),
    owner: 'Nat',
    estimatedMinutes: 95,
    budgetThb: 60,
    creditEstimateLow: 35,
    creditEstimateHigh: 85,
    actualCredits: 0,
    status: 'hook-ready',
    sourceIds: [],
    researchSummary: 'Demo context: map the repetitive lead follow-up workflow, manual time cost and safe automation boundaries.',
    factCheckSummary: 'Avoid promising fully autonomous sales outcomes; demonstrate bounded workflow steps and human approval.',
    scriptVersion: 1,
    hook: 'งานตอบ Lead ซ้ำ ๆ ที่กินวันละหนึ่งชั่วโมง ผมลองให้ AI Agent จัดการแทนทั้งหมด',
    script: '',
    storyboard: [],
    assetPrompts: [],
    capcutBrief: '',
    promptVersions: [],
    thumbnailVersions: [],
    publicationLinks: [],
    lessonsLearned: '',
    analyticsPostmortem: '',
    repurposingPlan: '',
    workflowEvents: [],
    policyChecks: {},
    riskLevel: 'low',
    createdAt: now,
    updatedAt: now,
    isDemo: true,
  },
  {
    id: 'project_penicillin',
    title: 'Why Penicillin Was an Accident',
    channelId: historyChannel.id,
    ideaId: 'history-5',
    series: 'Accidents That Changed the World',
    language: 'en',
    platforms: ['YouTube Shorts'],
    format: 'shorts',
    targetDurationSeconds: 58,
    deadline: addDays(today, -4),
    owner: 'Nat',
    estimatedMinutes: 170,
    budgetThb: 160,
    creditEstimateLow: 60,
    creditEstimateHigh: 140,
    actualCredits: 94,
    status: 'analytics-review',
    sourceIds: [],
    researchSummary: 'Demo research summary for the discovery context and the later development of penicillin.',
    factCheckSummary: 'The accidental observation is documented, but the path from observation to medicine required later scientific and industrial work.',
    scriptVersion: 3,
    hook: 'One of medicine’s biggest breakthroughs began with a contaminated dish.',
    script: 'Demo script record.',
    storyboard: ['0–4s contaminated dish reveal', '4–20s observation and context', '20–45s explain later development', '45–58s payoff'],
    assetPrompts: ['Macro laboratory dish, 1928 scientific workspace, documentary reconstruction'],
    capcutBrief: 'Standard documentary edit with archival-style lab visuals and explicit reconstruction label.',
    promptVersions: [],
    thumbnailVersions: [],
    publicationLinks: ['https://youtube.com/shorts/demo'],
    lessonsLearned: 'The visual reveal at second 18 retained viewers. The first title was too academic.',
    analyticsPostmortem: '',
    repurposingPlan: '',
    workflowEvents: [],
    policyChecks: { originalScript: true, sourcesPresent: true, claimsClassified: true, aiDisclosureReviewed: true, musicLicensed: true, templateRiskReviewed: true },
    riskLevel: 'low',
    createdAt: addDays(today, -10),
    updatedAt: addDays(today, -4),
    isDemo: true,
  },
];

const demoCredits: CreditEntry[] = [
  {
    id: 'credit_demo_1',
    projectId: 'project_penicillin',
    channelId: historyChannel.id,
    createdAt: addDays(today, -6),
    balanceBefore: 1800,
    balanceAfter: 1742,
    tool: 'video-clip',
    mode: 'standard',
    model: 'Seedance Mini',
    durationSeconds: 5,
    resolution: '720p',
    soundEnabled: false,
    generations: 4,
    regenerations: 1,
    usableOutputs: 3,
    completedVideo: false,
    visualStyle: 'Realistic Film',
    notes: 'Demo ledger: three usable motion shots.',
  },
  {
    id: 'credit_demo_2',
    projectId: 'project_penicillin',
    channelId: historyChannel.id,
    createdAt: addDays(today, -5),
    balanceBefore: 1742,
    balanceAfter: 1706,
    tool: 'ai-image',
    mode: 'standard',
    model: 'CapCut AI Image',
    durationSeconds: 0,
    resolution: 'other',
    soundEnabled: false,
    generations: 6,
    regenerations: 1,
    usableOutputs: 5,
    completedVideo: true,
    visualStyle: 'Historical documentary',
    notes: 'Demo ledger: final completed Short total 94 credits.',
  },
];

const demoAnalytics: AnalyticsEntry[] = [
  {
    id: 'analytics_demo_1',
    projectId: 'project_penicillin',
    channelId: historyChannel.id,
    recordedAt: addDays(today, -3),
    platform: 'youtube',
    impressions: 18600,
    views: 12400,
    viewedVsSwiped: 71.4,
    ctr: 5.8,
    averageViewDurationSeconds: 46,
    averagePercentageViewed: 88,
    retentionPoints: [100, 94, 91, 86, 82, 78, 75, 72, 69, 66, 63],
    watchHours: 158.4,
    subscribersGained: 92,
    returningViewers: 810,
    topCountries: ['United States', 'United Kingdom', 'Canada'],
    revenueThb: 0,
    rpmThb: 0,
    productionMinutes: 170,
    creditsUsed: 94,
    financialCostThb: 160,
    isDemo: true,
  },
  {
    id: 'analytics_demo_2',
    projectId: 'project_wojtek_short',
    channelId: historyChannel.id,
    recordedAt: addDays(today, -14),
    platform: 'youtube',
    impressions: 3900,
    views: 2180,
    viewedVsSwiped: 63,
    ctr: 4.6,
    averageViewDurationSeconds: 39,
    averagePercentageViewed: 74,
    retentionPoints: [100, 88, 82, 76, 71, 68, 64, 61, 58, 56, 53],
    watchHours: 23.6,
    subscribersGained: 14,
    returningViewers: 90,
    topCountries: ['United States', 'India', 'United Kingdom'],
    revenueThb: 0,
    rpmThb: 0,
    productionMinutes: 155,
    creditsUsed: 110,
    financialCostThb: 130,
    isDemo: true,
  },
  {
    id: 'analytics_demo_3',
    projectId: 'project_ai_boring_task',
    channelId: aiChannel.id,
    recordedAt: addDays(today, -9),
    platform: 'facebook',
    impressions: 5200,
    views: 2800,
    viewedVsSwiped: 61,
    ctr: 3.7,
    averageViewDurationSeconds: 31,
    averagePercentageViewed: 66,
    retentionPoints: [100, 84, 76, 70, 65, 59, 54, 50, 47, 45, 42],
    watchHours: 24.1,
    subscribersGained: 22,
    returningViewers: 110,
    topCountries: ['Thailand'],
    revenueThb: 0,
    rpmThb: 0,
    productionMinutes: 98,
    creditsUsed: 48,
    financialCostThb: 50,
    isDemo: true,
  },
];

const demoTasks: CalendarTask[] = [
  { id: 'task_factcheck', title: 'Fact-check Wojtek claims', date: addDays(today, -1), startTime: '09:00', durationMinutes: 35, type: 'research', projectId: 'project_wojtek_short', recurring: 'none', completed: true, completedAt: now, workflowPromptType: 'fact-check', sourceStatus: 'researching', targetStatus: 'sources-verified', missionRoute: 'prompts', autoGenerated: true, priority: 98, isDemo: true },
  { id: 'task_storyboard', title: 'Create Wojtek storyboard and shot list', date: today, startTime: '09:00', durationMinutes: 35, type: 'script', projectId: 'project_wojtek_short', recurring: 'none', completed: false, workflowPromptType: 'storyboard', sourceStatus: 'script-approved', targetStatus: 'storyboard', missionRoute: 'prompts', autoGenerated: true, priority: 100, isDemo: true },
  { id: 'task_ai_script', title: 'Write AI follow-up Shorts script', date: addDays(today, 1), startTime: '09:30', durationMinutes: 45, type: 'script', projectId: 'project_ai_boring_task', recurring: 'none', completed: false, workflowPromptType: 'shorts-script', sourceStatus: 'hook-ready', targetStatus: 'script-draft', missionRoute: 'prompts', autoGenerated: true, priority: 90, isDemo: true },
  { id: 'task_analytics', title: 'Post-mortem: Penicillin Short', date: addDays(today, 2), startTime: '10:00', durationMinutes: 30, type: 'analytics', projectId: 'project_penicillin', recurring: 'none', completed: false, workflowPromptType: 'analytics-postmortem', sourceStatus: 'analytics-review', targetStatus: 'repurpose', missionRoute: 'prompts', autoGenerated: true, priority: 85, isDemo: true },
  { id: 'task_batch', title: 'Batch production block', date: addDays(today, 3), startTime: '09:00', durationMinutes: 150, type: 'editing', recurring: 'weekly', completed: false, priority: 20, isDemo: true },
  { id: 'task_rest', title: 'Buffer / rest', date: addDays(today, 5), startTime: '10:00', durationMinutes: 60, type: 'rest', recurring: 'weekly', completed: false, priority: 5, isDemo: true },
];

const achievements: Achievement[] = [
  { id: 'achievement_first_channel', title: 'Studio Founded', description: 'Create the first channel blueprint.', icon: '🏗️', unlockedAt: now },
  { id: 'achievement_source_guard', title: 'Source Guard', description: 'Verify sources before script approval.', icon: '🛡️' },
  { id: 'achievement_first_publish', title: 'First Signal', description: 'Publish the first non-demo video.', icon: '📡' },
  { id: 'achievement_cost_control', title: 'Credit Controller', description: 'Complete five credit-ledger records.', icon: '⚙️' },
  { id: 'achievement_learning_loop', title: 'Learning Loop', description: 'Record analytics and a lesson for three videos.', icon: '🔁' },
];

const skills: SkillProgress = {
  research: 18,
  topicSelection: 14,
  hookWriting: 12,
  storytelling: 10,
  scriptWriting: 16,
  visualDirection: 9,
  editing: 8,
  thumbnail: 6,
  distribution: 7,
  analytics: 8,
  monetization: 5,
  consistency: 10,
};

const monetization: MonetizationPath[] = [
  { id: 'money_history_ads', channelId: historyChannel.id, name: 'YouTube advertising', type: 'platform', status: 'idea', estimatedMonthlyThb: 0, confirmedMonthlyThb: 0, nextAction: 'Reach eligibility using a Shorts + long-form watch-time strategy.' },
  { id: 'money_history_sponsor', channelId: historyChannel.id, name: 'Learning-product sponsorship', type: 'off-platform', status: 'idea', estimatedMonthlyThb: 4000, confirmedMonthlyThb: 0, nextAction: 'Build a 12-video proof set before outreach.' },
  { id: 'money_ai_leads', channelId: aiChannel.id, name: 'FlowBiz automation leads', type: 'lead-generation', status: 'testing', estimatedMonthlyThb: 15000, confirmedMonthlyThb: 0, nextAction: 'Add one clear audit CTA to the top-performing practical workflow.' },
];

export const createSeedWorkspace = (): Workspace => ({
  schemaVersion: 3,
  id: 'default',
  name: 'Creator Empire — Nat',
  createdAt: now,
  updatedAt: now,
  ideas: structuredClone(seedIdeas),
  channels: [historyChannel, aiChannel],
  projects: demoProjects,
  sources: [
    { id: 'source_wojtek_iwm', projectId: 'project_wojtek_short', title: 'Wojtek memorial record', url: 'https://memorials.iwm.org.uk/memorial/78065', publisher: 'Imperial War Museums', accessedAt: today, claimType: 'documented', notes: 'Supports the unit association and memorial context.' },
    { id: 'source_wojtek_museum', projectId: 'project_wojtek_short', title: 'Wojtek background record', url: 'https://www.nms.ac.uk/explore-our-collections/stories/scottish-history-and-archaeology/wojtek-the-bear/', publisher: 'National Museums Scotland', accessedAt: today, claimType: 'context', notes: 'Use cautiously; distinguish documented record from later retellings.' },
  ],
  prompts: [],
  calendarTasks: demoTasks,
  credits: demoCredits,
  analytics: demoAnalytics,
  policies: structuredClone(seedPolicies),
  monetization,
  simulations: [],
  achievements,
  skills,
  xp: 760,
  level: 7,
  streak: 3,
  earnedEvents: ['seed:studio-founded'],
  focus: { mode: 'channel', activeChannelId: historyChannel.id, activeProjectId: 'project_wojtek_short', activeTaskId: 'task_storyboard', updatedAt: now },
  settings: {
    locale: 'th',
    timezone: 'Asia/Bangkok',
    weeklyHoursAvailable: 12,
    capcutBalance: 1634,
    soundEnabled: false,
    reducedMotion: false,
    onboardingComplete: false,
    workflowMode: 'manual',
    aiProvider: 'openai',
    openAiModel: 'gpt-5.6-luna',
    openAiAdvancedModel: 'gpt-5.6-terra',
    openAiInputUsdPer1M: 0.2,
    openAiOutputUsdPer1M: 1.2,
    openAiAdvancedInputUsdPer1M: 2,
    openAiAdvancedOutputUsdPer1M: 12,
    openAiSearchUsdPerQuery: 0.01,
    geminiModel: 'gemini-3.5-flash',
    geminiThinkingLevel: 'low',
    geminiSearchUsdPerQuery: 0.014,
    connectedAiEnabled: false,
    connectedAiProxyUrl: '/api/ai/generate',
    sqliteStorageEnabled: true,
    activeChannelLimit: 2,
  },
});
