import type { PolicyRule } from '../domain/types.js';

export const seedPolicies: PolicyRule[] = [
  {
    id: 'youtube-ypp-early',
    platform: 'youtube',
    country: 'Thailand',
    topic: 'Expanded YPP / early fan-funding access',
    summary: 'Track early YPP separately from advertising revenue. Eligibility can depend on subscriber, upload, watch-hour or Shorts-view thresholds and program availability.',
    sourceUrl: 'https://support.google.com/youtube/answer/13429240',
    lastVerifiedAt: '2026-08-06',
    status: 'active',
    notes: 'Editable policy record. Confirm inside YouTube Studio before relying on eligibility.',
  },
  {
    id: 'youtube-ypp-ads',
    platform: 'youtube',
    country: 'Thailand',
    topic: 'Advertising-revenue eligibility',
    summary: 'Model advertising-revenue progress separately from early YPP. Shorts Feed watch time does not count toward the long-form public watch-hour route.',
    sourceUrl: 'https://support.google.com/youtube/answer/72851',
    lastVerifiedAt: '2026-08-06',
    status: 'active',
    notes: 'Do not present the progress forecast as a guarantee of approval.',
  },
  {
    id: 'youtube-inauthentic',
    platform: 'youtube',
    country: 'global',
    topic: 'Inauthentic, repetitive, or mass-produced content risk',
    summary: 'Flag channels whose videos are minimally varied, template-like, interchangeable, or mass-produced without meaningful original value.',
    sourceUrl: 'https://support.google.com/youtube/answer/1311392',
    lastVerifiedAt: '2026-08-06',
    status: 'active',
    notes: 'Evaluate channel-level repetition, not only one video.',
  },
  {
    id: 'youtube-synthetic',
    platform: 'youtube',
    country: 'global',
    topic: 'Altered or synthetic content disclosure',
    summary: 'Realistic synthetic or meaningfully altered scenes that did not occur may require disclosure. Disclosure itself is not treated as an automatic monetization penalty.',
    sourceUrl: 'https://support.google.com/youtube/answer/14328491',
    lastVerifiedAt: '2026-08-06',
    status: 'active',
    notes: 'Use project-specific review; do not rely on a blanket channel setting.',
  },
  {
    id: 'facebook-content-monetization',
    platform: 'facebook',
    country: 'global',
    topic: 'Facebook Content Monetization',
    summary: 'Treat availability as account- and region-specific. Store invitation or Professional Dashboard status rather than a universal threshold.',
    sourceUrl: 'https://about.fb.com/news/2026/03/creator-fast-track-grow-your-audience-earn-money-on-facebook/',
    lastVerifiedAt: '2026-08-06',
    status: 'active',
    notes: 'Original content, qualified views, and meaningful watch time remain important signals.',
  },
  {
    id: 'facebook-original',
    platform: 'facebook',
    country: 'global',
    topic: 'Original content priority',
    summary: 'Minor edits or unoriginal reposting may be deprioritized or become ineligible. Preserve evidence of original scripting, production, and transformation.',
    sourceUrl: 'https://about.fb.com/news/2026/03/rewarding-original-creators-on-facebook/',
    lastVerifiedAt: '2026-08-06',
    status: 'active',
  },
  {
    id: 'tiktok-rewards',
    platform: 'tiktok',
    country: 'global',
    topic: 'Creator Rewards regional eligibility',
    summary: 'Qualifying videos are expected to be original, high quality, longer than one minute, and published in an eligible region. Keep regional availability editable.',
    sourceUrl: 'https://support.tiktok.com/en/business-and-creator/creator-rewards-program/how-is-the-creator-rewards-program-different-from-the-tiktok-creator-fund',
    lastVerifiedAt: '2026-08-06',
    status: 'uncertain',
    notes: 'Confirm country support in the creator account before planning revenue.',
  },
  {
    id: 'tiktok-shop-th',
    platform: 'tiktok',
    country: 'Thailand',
    topic: 'TikTok Shop creator access',
    summary: 'Model TikTok Shop/Affiliate separately from Creator Rewards. Requirements can include follower, age, location, and account-health criteria.',
    sourceUrl: 'https://seller-th.tiktok.com/university/essay?knowledge_id=2224597307737872&lang=en',
    lastVerifiedAt: '2026-08-06',
    status: 'active',
    notes: 'Check the current Seller University page and in-app eligibility.',
  },
  {
    id: 'capcut-credit-operation',
    platform: 'capcut',
    country: 'global',
    topic: 'Credit deduction workflow',
    summary: 'CapCut shows the credit requirement before confirming an eligible AI operation. Record actual balance before and after; do not hard-code credits per video.',
    sourceUrl: 'https://www.capcut.com/help/how-to-use-credits',
    lastVerifiedAt: '2026-08-06',
    status: 'active',
  },
  {
    id: 'capcut-credit-reference',
    platform: 'capcut',
    country: 'global',
    topic: 'Credit value reference',
    summary: 'CapCut currently presents a reference value for credits, but model and action pricing can vary. Use the user ledger as the operational source of truth.',
    sourceUrl: 'https://www.capcut.com/help/credits-in-capcut',
    lastVerifiedAt: '2026-08-06',
    status: 'active',
  },
];
